/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/myoperator/jobflowoperator/pkg/apis/daemonjob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDaemonJobs implements DaemonJobInterface
type FakeDaemonJobs struct {
	Fake *FakeApiV1alpha1
	ns   string
}

var daemonjobsResource = schema.GroupVersionResource{Group: "api.practice.com", Version: "v1alpha1", Resource: "daemonjobs"}

var daemonjobsKind = schema.GroupVersionKind{Group: "api.practice.com", Version: "v1alpha1", Kind: "DaemonJob"}

// Get takes name of the daemonJob, and returns the corresponding daemonJob object, and an error if there is any.
func (c *FakeDaemonJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DaemonJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(daemonjobsResource, c.ns, name), &v1alpha1.DaemonJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaemonJob), err
}

// List takes label and field selectors, and returns the list of DaemonJobs that match those selectors.
func (c *FakeDaemonJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DaemonJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(daemonjobsResource, daemonjobsKind, c.ns, opts), &v1alpha1.DaemonJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DaemonJobList{ListMeta: obj.(*v1alpha1.DaemonJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.DaemonJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested daemonJobs.
func (c *FakeDaemonJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(daemonjobsResource, c.ns, opts))

}

// Create takes the representation of a daemonJob and creates it.  Returns the server's representation of the daemonJob, and an error, if there is any.
func (c *FakeDaemonJobs) Create(ctx context.Context, daemonJob *v1alpha1.DaemonJob, opts v1.CreateOptions) (result *v1alpha1.DaemonJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(daemonjobsResource, c.ns, daemonJob), &v1alpha1.DaemonJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaemonJob), err
}

// Update takes the representation of a daemonJob and updates it. Returns the server's representation of the daemonJob, and an error, if there is any.
func (c *FakeDaemonJobs) Update(ctx context.Context, daemonJob *v1alpha1.DaemonJob, opts v1.UpdateOptions) (result *v1alpha1.DaemonJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(daemonjobsResource, c.ns, daemonJob), &v1alpha1.DaemonJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaemonJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDaemonJobs) UpdateStatus(ctx context.Context, daemonJob *v1alpha1.DaemonJob, opts v1.UpdateOptions) (*v1alpha1.DaemonJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(daemonjobsResource, "status", c.ns, daemonJob), &v1alpha1.DaemonJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaemonJob), err
}

// Delete takes name of the daemonJob and deletes it. Returns an error if one occurs.
func (c *FakeDaemonJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(daemonjobsResource, c.ns, name), &v1alpha1.DaemonJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDaemonJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(daemonjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DaemonJobList{})
	return err
}

// Patch applies the patch and returns the patched daemonJob.
func (c *FakeDaemonJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DaemonJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(daemonjobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DaemonJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaemonJob), err
}
