apiVersion: api.practice.com/v1alpha1
kind: JobTemplate
metadata:
  name: job1-template
spec:
  jobTemplate:
    template:
      spec:
        containers:
          - image: busybox:1.28
            command:
              - sh
              - -c
              - sleep 10s
            imagePullPolicy: IfNotPresent
            name: nginx
---
apiVersion: api.practice.com/v1alpha1
kind: JobTemplate
metadata:
  name: job2-template
spec:
  jobTemplate:
    template:
      spec:
        containers:
          - image: busybox:1.28
            command:
              - sh
              - -c
              - sleep 10s
            imagePullPolicy: IfNotPresent
            name: nginx

