apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobflowoperator-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app: jobflowoperator-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: jobflowoperator-controller
    spec:
      nodeName: vm-0-12-centos # 只调度到这个节点上
      serviceAccountName: jobflowoperator-sa # 配置service account
      containers:
        - name: jobflowoperator # 控制器镜像
          image: jobflowoperator:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: "Release"
              value: "1"
          ports:
            - containerPort: 80

