apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobflow-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app: jobflow-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: jobflow-controller
    spec:
      nodeName: vm-0-16-centos # 只调度到这个节点上
      serviceAccountName: jobflow-sa # 配置service account
      containers:
        - name: jobflow # 控制器镜像
          image: jobflowoperator:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: "Release"
              value: "1"
          ports:
            - containerPort: 80

