/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	daemonjobv1alpha1 "github.com/myoperator/jobflowoperator/pkg/apis/daemonjob/v1alpha1"
	versioned "github.com/myoperator/jobflowoperator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/myoperator/jobflowoperator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/myoperator/jobflowoperator/pkg/client/listers/daemonjob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DaemonJobInformer provides access to a shared informer and lister for
// DaemonJobs.
type DaemonJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DaemonJobLister
}

type daemonJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDaemonJobInformer constructs a new informer for DaemonJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDaemonJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDaemonJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDaemonJobInformer constructs a new informer for DaemonJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDaemonJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().DaemonJobs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().DaemonJobs(namespace).Watch(context.TODO(), options)
			},
		},
		&daemonjobv1alpha1.DaemonJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *daemonJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDaemonJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *daemonJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&daemonjobv1alpha1.DaemonJob{}, f.defaultInformer)
}

func (f *daemonJobInformer) Lister() v1alpha1.DaemonJobLister {
	return v1alpha1.NewDaemonJobLister(f.Informer().GetIndexer())
}
